from . import views
from django.urls import path
from django.urls import include

urlpatterns = [
    path('create', views.create,name="create"),
    path('update/<int:post_id>/', views.update, name='update'),

    #path('preview/<str:id>/', views.preview,name="preview"),
    path('', views.post,name="home"),
    path('fest', views.fest,name="fest"),
    path('login', views.login,name="login"),
    #path('updatepost/<str:id>/', views.updatepost,name="updatepost"),
    #path('register/<str:id>/', views.userreg,name="register"),
    path('addreport/<str:id>/', views.addreport,name="addreport"),
    path('viewreport/<str:id>/', views.viewreport,name="viewreport"),
    path('register/<str:id>/', views.reg,name="reg"),
    #path('sup', views.suplogin,name="sup"),
    #path('post_d', views.post_d,name="post_d"),
    #path('admin@post',views.admin_post,name="admin@post"),
    path('krctcoordinator',views.krctcoordinator,name="krctco"),
    path('krcecoordinator',views.krcecoordinator,name="krceco"),
    path('mkcecoordinator',views.mkcecoordinator,name="mkceco"),
    path('krctiqac',views.krctiqac,name="krctiqac"),
    path('krctiqac_archive',views.krctiqac_archive,name="krctiqac_archive"),
    path('krceiqac_archive',views.krceiqac_archive,name="krceiqac_archive"),
    path('mkceiqac_archive',views.mkceiqac_archive,name="mkceiqac_archive"),
    path('krceiqac',views.krceiqac,name="krceiqac"),
    path('mkceiqac',views.mkceiqac,name="mkceiqac"),
    path('krce@post',views.krce_post,name="krce@post"),
    path('krct@post',views.krct_post,name="krct@post"),
    path('mkce@post',views.mkce_post,name="mkce@post"),
    path('logout',views.logout,name="logout"),
    
    path('delete/<str:id>/',views.delete,name="delete"),
    path('approve/<str:id>/',views.approve,name="approve"),
    path('close/<str:id>/',views.close,name="close"),
    path('open/<str:id>/',views.open,name="open"),
    path('archive/<str:id>/',views.archive,name="archive"),
    path('undo/<str:id>/',views.undo,name="undo"),
    path('detail/<str:id>/',views.detail,name="detail"),
    path('regdetail/<str:id>/',views.regdetail,name="userdetail"),
    path('admindetail/<str:id>/',views.admindetail,name="admindetail"),
    path('postadmindetail/<str:id>/',views.postadmindetail,name="postadmindetail"),
    #path('reqdetail/<str:id>/',views.reqdetail,name="reqdetail"),
    #path('active',views.active,name="active"),
    #path('posactive',views.active,name="posactive"),
    path('ac/<str:id>/',views.ac,name="ac"),
]
