# Generated by Django 4.0.4 on 2023-03-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_approvedpost_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedpost',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
