# Generated by Django 4.0.4 on 2023-03-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_delete_approvedpost_post_approved_post_cllg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dept',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='etype',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
