# Generated by Django 4.0.4 on 2023-03-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_userreg_alter_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='fromcllg',
            field=models.CharField(default=False, max_length=300),
        ),
    ]
