# Generated by Django 4.0.4 on 2023-03-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_userreg_fromcllg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='event',
            field=models.CharField(default=False, max_length=300),
        ),
    ]
