# Generated by Django 4.0.4 on 2023-03-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_userreg_email_alter_userreg_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='cllgname',
            field=models.CharField(max_length=300),
        ),
    ]
