# Generated by Django 4.0.4 on 2023-03-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_post_darkmode_post_lightmode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
