# Generated by Django 4.0.4 on 2023-03-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark', models.BooleanField(default=False, verbose_name='dark')),
                ('light', models.BooleanField(default=True, verbose_name='light')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='darkmode',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lightmode',
        ),
    ]
