# Generated by Django 4.0.4 on 2023-04-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_post_reglink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default=False, upload_to='img/%m-%y'),
        ),
    ]
