# Generated by Django 4.2 on 2023-05-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_alter_post_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mode',
        ),
        migrations.DeleteModel(
            name='UserReg',
        ),
        migrations.AddField(
            model_name='post',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='is_archive'),
        ),
    ]
