# Generated by Django 4.2 on 2023-05-29 17:58

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_delete_mode_delete_userreg_post_is_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default=False, storage=post.models.OverwriteStorage, upload_to='img/%m-%y'),
        ),
    ]
