# Generated by Django 4.2 on 2023-06-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_userreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='closed'),
        ),
    ]
